name: CI/CD

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-build
        with:
          node_version: ${{ matrix.node-version }}
